name: Linux Release

on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  linux:
    name: Linux

    runs-on: ubuntu-20.04

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install libsdl3-dev zlib1g-dev

      - name: Cache cmake build
        uses: actions/cache@v4
        with:
          path: build
          key: linux-cmake-v3

      - name: Configure
        run: |
          cmake \
            -B build \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            # EOL

      - name: Build
        run: |
          cmake \
            --build build \
            -j $(nproc) \
            # EOL

      - name: Upload
        run: |
          cd build
          tar -czvf fallout-ce-linux.tar.gz fallout-ce
          gh release upload ${{ github.event.release.tag_name }} fallout-ce-linux.tar.gz
          rm fallout-ce-linux.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
